;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/ContextEffects/DT_ContextSurfaceTypeTags.DT_ContextSurfaceTypeTags
+GameplayTagTableList=/Game/ContextEffects/DT_EventTags.DT_EventTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="State.Fire",DevComment="")
+GameplayTagList=(Tag="State.Healing",DevComment="")
+GameplayTagList=(Tag="State.Water",DevComment="")

